//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockroomBinar.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliveries
    {
        public int ID { get; set; }
        public Nullable<int> IDDeliveries { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public Nullable<int> MaxQuantity { get; set; }
        public Nullable<int> ReadyQuantity { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
