//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockroomBinar.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDProducts
    {
        public string ID { get; set; }
        public string NameProduct { get; set; }
    
        public virtual ProductsForEngraving ProductsForEngraving { get; set; }
        public virtual PlasticProducts PlasticProducts { get; set; }
    }
}
