//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockroomBinar.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsForEngraving
    {
        public string ID { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public byte[] Profile { get; set; }
    
        public virtual IDProducts IDProducts { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
